#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <filename> <number_of_files>"
    exit 1
fi

input_file="$1"
num_files="$2"

total_lines=$(wc -l < "$input_file")
lines_per_file=$(( (total_lines + num_files - 1) / num_files ))
suffix_length=$(printf "%d" $(($num_files-1)) | wc -c)

split --numeric-suffixes=1 --suffix-length=$suffix_length -l "$lines_per_file" "$input_file" "${input_file}_part_"

for i in $(seq 1 $num_files)
do
    suffix=$(printf "%0${suffix_length}d" $i)
    mv "${input_file}_part_${suffix}" "passwords_${i}.txt"
done
